sudo: required

language: bash

services:
  - docker

before_install:
  - docker run --rm -i hadolint/hadolint < Dockerfile

install:
  - docker build -t intelliops/travis-release:build -f Dockerfile .
  - docker run --name travis-release intelliops/travis-release:build

script:
  - docker ps -a
  - docker stop travis-release
  - docker rm -f travis-release

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then ./release.sh; fi
